### ISSUE TITLE
Report Error

### ISSUE THREAD

**Issue by MeeMeChu** [MinecraftChannel/VoucherTopup#10]
ทำไมตอนคนเติมเยอะ ๆ มันขึ้น error 
แบบเติมหลัก พัน ขึ้นไป มันจะ Error แต่เงินเข้าปกติ
แต่มันไม่ รันตัวคำสั่งที่ตั้งไว้

**Comment by ST4RCHASER** [comment]
นั้นรบกวนขอ Error ที่ครับผม เดียวตรวจสอบให้นะครับ ส่งมาเป็น log เลยก็ได้ครับผม

**Comment by MeeMeChu** [comment]
เวลาที่ลอง 12:53:33 ครับ ใน log

ในวันที่ พฤ. 5 ส.ค. 2021 เวลา 11:26 _StarChaser ***@***.***>
เขียนว่า:

**Comment by maythiwat** [comment]
แก้ไขปัญหา string "1,000.00" เรียบร้อยแล้วนะครับ
สามารถดาวน์โหลด Build ล่าสุดได้เลยครับ
https://ci.srv.in.th/job/VoucherTopup/4/

**Comment by MeeMeChu** [comment]
ลองตัว Build ล่าสุดแล้วขึ้นแบบนี้อะครับ
An internal error occurred while attempting to perform this command
[2021-08-05-3.log](https://github.com/MinecraftChannel/VoucherTopup/files/6937284/2021-08-05-3.log)
