### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by MeeMeChu** [MinecraftChannel/VoucherTopup#12]
ขอโทษด้วยครับที่รบกวนบ่อย
พอดี ตอนเติมเข้า คำสั่งที่มีใช้ตัวเลขมันไม่มีผลอะครับ แบบ point add %amount% player มันขึ้น 0 ตลอด

**Comment by maythiwat** [comment]
ตรงนี้ไม่ได้เป็น Bug ของ Code เรานะครับ

ขอแนะนำให้ไปสอบถามที่กลุ่ม Minecraft Channel หรือ Discord แทนครับ
https://discord.gg/eu73JU6ec3

Issue ใน GitHub มีไว้สำหรับแจ้ง Bug ใน Code หลักของปลั๊กอินเท่านั้น ไม่ได้ไว้ใช้สอบถามครับ 😂
