### ISSUE TITLE
มีปัญหาในการรันคำสั่งครับ

### ISSUE THREAD

**Issue by ptpkk1903** [MinecraftChannel/VoucherTopup#3]
คือผมลองเปิดเซิฟ 1.8.8 แล้วเข้าไปในเซิฟ จากนั้นพิม /voucher แล้วมันขึ้น

an internal error occurred while attempting to perform this command

เป็นเพราะอะไรครับ

**Comment by ptpkk1903** [comment]
> คือผมลองเปิดเซิฟ 1.8 แล้วเข้าไปในเซิฟ จากนั้นพิม /voucher แล้วมันขึ้น
> 
> an internal error occurred while attempting to perform this command
> 
> เป็นเพราะอะไรครับ

**Comment by ST4RCHASER** [comment]
รบกวนลองส่ง error log ให้หน่อยครับผม เดียวผมจะลองเช็คอีกทีให้ครับผม
