### ISSUE TITLE
สามารถเอาไปทำอะไรได้บ้างครับ

### ISSUE THREAD

**Issue by dofphins** [MinecraftChannel/VoucherTopup#4]
สามารถตั้งค่าให้ของตามจำนวนที่เติมได้รึป่าวครับ (ขอวิธีด้วยครับ)

**Comment by ST4RCHASER** [comment]
สามารถเข้าไปตรวจสอบได้ที่นี้เลยครับผมส่วนสำหรับ [config.yml](https://github.com/MinecraftChannel/VoucherTopup/blob/master/src/main/resources/config.yml)

**Comment by ST4RCHASER** [comment]
Closed
