### ISSUE TITLE
.

### ISSUE THREAD

**Issue by MeowSiX** [MinecraftChannel/VoucherTopup#5]

**Comment by MeowSiX** [comment]
ผมเอาไปทำ Nukkit แล้วตามนั้นเลยครับ

**Comment by maythiwat** [comment]
จากเนื้อหาก่อนหน้านี้ ของ Issue นี้
เป็นการนำไปดัดแปลงเอง ซึ่งส่วนนี้ทางเราตอบให้ไม่ได้ครับ
