### ISSUE TITLE
สอบถามหน่อยครับ : )

### ISSUE THREAD

**Issue by Bank1807** [MinecraftChannel/VoucherTopup#7]
อยากทราบว่าวิธีปรับให้ได้ Points x3

สมมุติเติม 10 wallet ก็จะได้ 30 points ครับ ต้องทำยังไงหรอครับ

**Comment by ST4RCHASER** [comment]
อัพให้เรียบร้อยแล้วครับผม ของแก้ใน config ใช้งานได้เลยครับ
